server:
  port: 10000

spring:
  config:
    import: application-common.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 359070895590-sut0ea0s2qif2pe4jjlkm2o6570u2lu0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 247654714067061
            client-secret: c954a597fe256e33871d55ec7b4e8097
            scope:
              - email
              - public_profile
          naver:
            client-id: 8goLGUVRLcR5yjhS8d4u
            client-secret: P1uTpGTAxy
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:10000/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.